version: '3.5'

services: 
  mongodb: 
    image: mongo:4.2.2
    container_name: 'mongodb'
    ports: 
      - '27017:27017'
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes: 
      - ./data/db:/data/db
    restart: on-failure
    logging: 
      driver: 'json-file'
      options: 
        max-size: '30m'
        max-file: '1'
    networks: 
      - mongo_net

networks: 
  mongo_net:
    name: mongo_net