version: '3'

services:
  es:
    image: registry.cn-hangzhou.aliyuncs.com/open_zail/elasticsearch:7.5.1
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200