version: '3'

services:
  es:
    image: registry.cn-hangzhou.aliyuncs.com/open_zail/elasticsearch:7.5.1
    container_name: es
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config:/usr/share/elasticsearch/config
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200