version: '3'

services:
    redis:
        image: registry.cn-hangzhou.aliyuncs.com/open_zail/redis:5.0
        container_name: "redis-server"
        ports:
            - "6379:6379"
        volumes:
            #- ./data:/data:z
            - ./config/redis.conf:/usr/local/etc/redis/redis.conf
        restart: on-failure
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'